before_install: "travis_retry npm install"
install: "./node_modules/.bin/travisaction $CI_ACTION install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/travisaction $CI_ACTION before_script"
script: "./node_modules/.bin/travisaction $CI_ACTION script"
branches:
  except:
    - v1-train
    - v1.1.0hd
    - v1.0.0
    - v1.0.1
env:
  - CI_ACTION=gjslint
  - CI_ACTION=test_agent
  - CI_ACTION=marionette_js
  - CI_ACTION=jshint
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/bluetooth/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/browser/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/calendar/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/camera/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/cards_view/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/clock/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/contacts/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/cost_control/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/dialer/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/email/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/everythingme/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/fmradio/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/ftu/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/gallery/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/homescreen/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/keyboard/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/lockscreen/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/messages/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/music/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/persona/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/settings/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/system/manifest.ini
  - CI_ACTION=gaia_ui_tests GAIATEST_MANIFEST=tests/videoplayer/manifest.ini
matrix:
  allow_failures:
    - env: CI_ACTION=jshint
notifications:
  irc:
    channels:
      - "irc.mozilla.org#gaia"
