before_install: "travis_retry npm install --registry http://54.204.30.62:8080"
install: "./node_modules/.bin/travisaction $CI_ACTION install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/travisaction $CI_ACTION before_script"
script: "./node_modules/.bin/travisaction $CI_ACTION script"
branches:
  except:
    - v1-train
    - v1.1.0hd
    - v1.0.0
    - v1.0.1
env:
  - CI_ACTION=marionette_js
matrix:
  allow_failures:
    - env: CI_ACTION=jshint
notifications:
  irc:
    on_success: change
    channels:
      - "irc.mozilla.org#gaia"
